default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cmm_demo_app_development
  host: localhost

test:
  <<: *default
  database: cmm_demo_app_test
  host: localhost
